FROM python:3.10.12-slim-bullseye@sha256:2daf07926ccdff5dbeef6bee46cc5bb07322f417c102609601177a1559156385 AS builder

RUN apt-get update \
 && apt-get install --yes curl

ENV POETRY_VERSION=1.7.1  PATH="${PATH}:/root/.local/bin"

COPY poetry.lock pyproject.toml ./

RUN curl -sSL https://install.python-poetry.org | python3 - \
 && poetry export --output=requirements.txt --with dev

FROM python:3.10.12-slim-bullseye@sha256:2daf07926ccdff5dbeef6bee46cc5bb07322f417c102609601177a1559156385

RUN useradd --create-home todoapp
USER todoapp
WORKDIR /home/todoapp

COPY example_application ./example_application
COPY example_application_tests ./example_application_tests
COPY --from=builder requirements.txt ./requirements.txt

RUN pip3 install -r requirements.txt

EXPOSE 8000

CMD python3 -m coverage run -m pytest -vvv example_application_tests && python3 -m coverage report
