FROM python:3.10.12-slim-bullseye@sha256:2daf07926ccdff5dbeef6bee46cc5bb07322f417c102609601177a1559156385

RUN apt-get update \
 && apt-get install --yes  curl \
 && apt-get clean autoclean \
 && apt-get autoremove --yes \
 && rm -rf /var/lib/{apt,dpkg,cache,log}/ \
 && useradd --create-home todoapp

USER todoapp
WORKDIR /home/todoapp

ENV POETRY_VERSION=1.7.1  PATH="${PATH}:/home/todoapp/.local/bin"

COPY example_application ./example_application
COPY example_application_tests ./example_application_tests
COPY poetry.lock pyproject.toml ./

RUN curl -sSL https://install.python-poetry.org | python3 - \
 && poetry config virtualenvs.in-project true \
 && poetry install

EXPOSE 8000

CMD .venv/bin/python3 -m coverage run -m pytest -vvv example_application_tests && .venv/bin/python3 -m coverage report

