FROM python:3.10.12-slim-bullseye@sha256:2daf07926ccdff5dbeef6bee46cc5bb07322f417c102609601177a1559156385 AS builder

RUN apt-get update \
 && apt-get install --yes curl

ENV POETRY_VERSION=1.7.1  PATH="${PATH}:/root/.local/bin"

COPY example_application ./example_application
COPY poetry.lock pyproject.toml ./

RUN curl -sSL https://install.python-poetry.org | python3 - \
 && poetry config virtualenvs.in-project true \
 && poetry install --without dev

FROM python:3.10.12-slim-bullseye@sha256:2daf07926ccdff5dbeef6bee46cc5bb07322f417c102609601177a1559156385

RUN useradd --create-home todoapp
USER todoapp
WORKDIR /home/todoapp

COPY example_application ./example_application
COPY --from=builder ./.venv/ ./venv

EXPOSE 8000

CMD ./venv/bin/python3 -m uvicorn example_application.main:app --host 0.0.0.0
